version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
      POSTGRES_JDBC_URL: ${POSTGRES_JDBC_URL}
    depends_on:
      - db
